import type { QueueEntry } from './types';

const MINUTE = 60;
const HOUR = 60 * MINUTE;

export const QUEUE_REGISTRY: readonly QueueEntry[] = [
  // --- Platforma, část 1 ----------------------------------------------------
  {
    name: 'platform.webhook_fanout',
    domain: 'platform',
    owner: 'P04',
    description: 'Z události webhooku vyrobí doručení pro každý odebírající endpoint.',
    retryLimit: 5,
    retryBackoff: true,
    retryDelaySeconds: 5,
    expireInSeconds: 5 * MINUTE,
    deadLetter: true,
    payloadFields: ['event_id', 'created_at'],
    source: 'část 1, 3.8',
  },
  {
    name: 'platform.webhook_deliver',
    domain: 'platform',
    owner: 'P04',
    description: 'Jedno HTTP doručení. Retry řídí aplikace přes next_attempt_at, ne pg-boss.',
    retryLimit: 0,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 2 * MINUTE,
    singletonKeyTemplate: 'delivery:<delivery_id>',
    deadLetter: false,
    payloadFields: ['delivery_id', 'created_at'],
    source: 'část 1, 3.8',
  },
  {
    name: 'platform.maintain_partitions',
    domain: 'platform',
    owner: 'P03',
    description: 'Zajistí existenci partition pro aktuální a další tři měsíce.',
    cron: '0 2 * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 30 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 1, 2.1',
  },
  {
    name: 'platform.cleanup_sessions',
    domain: 'platform',
    owner: 'P04',
    description: 'Maže relace starší než 30 dní od skončení.',
    cron: '15 2 * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 15 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 1, 3.2',
  },
  {
    name: 'platform.cleanup_idempotency',
    domain: 'platform',
    owner: 'P04',
    description: 'Maže vypršené záznamy idempotenčních klíčů.',
    cron: '25 2 * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 15 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 1, 4.4 (název odvozen P01)',
  },
  {
    name: 'platform.cleanup_audit_log',
    domain: 'platform',
    owner: 'P04',
    description: 'Retence auditu podle AUDIT_RETENTION_MONTHS.',
    cron: '35 2 * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 30 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 1, 3.7 a 4.9 (název odvozen P01)',
  },
  {
    name: 'platform.purge_workspaces',
    domain: 'platform',
    owner: 'P04',
    description: 'Trvale odstraní měkce smazané projekty po uplynutí lhůty.',
    cron: '45 2 * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 1 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: true,
    payloadFields: [],
    source: 'část 1, 3.3',
  },
  {
    name: 'platform.backup',
    domain: 'platform',
    owner: 'P16',
    description: 'Plánovaná záloha podle BACKUP_SCHEDULE_CRON.',
    cron: '0 3 * * *',
    retryLimit: 1,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 4 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: true,
    payloadFields: [],
    source: 'část 1, 3.14',
  },
  {
    name: 'platform.backup_verify',
    domain: 'platform',
    owner: 'P16',
    description: 'Týdenní mlain backup verify nad poslední zálohou.',
    cron: '0 4 * * 0',
    retryLimit: 1,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 4 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: true,
    payloadFields: [],
    source: 'část 1, 3.14',
  },

  // --- Kontakty, souhlasy, segmenty a GDPR, část 2 -------------------------
  {
    name: 'contacts.import',
    domain: 'contacts',
    owner: 'P11',
    description: 'Import CSV po dávkách s checkpointy. Jeden běžící import na projekt.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 6 * HOUR,
    singletonKeyTemplate: '<workspace_id>',
    deadLetter: true,
    payloadFields: ['import_id', 'workspace_id'],
    source: 'část 2, 4.6',
  },
  {
    name: 'contacts.export',
    domain: 'contacts',
    owner: 'P11',
    description: 'Export s kurzorem na serveru, dávky 5 000 řádků, gzip.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 2 * HOUR,
    deadLetter: true,
    payloadFields: ['export_id', 'workspace_id'],
    source: 'část 2, 4.7',
  },
  {
    name: 'contacts.bulk_delete',
    domain: 'contacts',
    owner: 'P07',
    description: 'Hromadné mazání po dávkách 5 000.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 2 * HOUR,
    deadLetter: true,
    payloadFields: ['operation_id', 'workspace_id'],
    source: 'část 2, 4.3',
  },
  {
    name: 'contacts.bulk_tag',
    domain: 'contacts',
    owner: 'P07',
    description: 'Hromadné přidání a odebrání štítků nad skupinou přes 5 000 kontaktů.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 2 * HOUR,
    deadLetter: true,
    payloadFields: ['operation_id', 'workspace_id'],
    source: 'část 2, 4.4',
  },
  {
    name: 'contacts.bulk_vocative_review',
    domain: 'contacts',
    owner: 'P11',
    description: 'Hromadné vyřízení fronty ke kontrole oslovení po dávkách 5 000.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 2 * HOUR,
    deadLetter: true,
    payloadFields: ['operation_id', 'workspace_id'],
    source: 'část 2, 4.5',
  },
  {
    name: 'contacts.strip_attribute',
    domain: 'contacts',
    owner: 'P07',
    description: 'Odstraní klíč z attributes po dávkách 10 000 po smazání vlastního pole.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 2 * HOUR,
    deadLetter: true,
    payloadFields: ['workspace_id', 'field_key'],
    source: 'část 2, 4.2',
  },
  {
    name: 'contacts.refingerprint',
    domain: 'contacts',
    owner: 'P07',
    description: 'Po rotaci SECRET_KEY doplní otisky pod novým pokolením, dávky 10 000.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 4 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: true,
    payloadFields: ['key_id', 'cursor'],
    source: 'část 2, 6',
  },
  {
    name: 'contacts.recompute_greeting',
    domain: 'contacts',
    owner: 'P07',
    description: 'Přepočet oslovení po změně nastavení projektu.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 2 * HOUR,
    singletonKeyTemplate: '<workspace_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'cursor'],
    source: 'část 2, 4.5',
  },
  {
    name: 'contacts.cleanup_after_reactivation',
    domain: 'contacts',
    owner: 'P07',
    description: 'Naplánovaný úklid po reaktivační kampani, výchozí za 14 dní.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 2 * HOUR,
    deadLetter: true,
    payloadFields: ['workspace_id', 'segment_id', 'action'],
    source: 'část 2, 5.8',
  },
  {
    name: 'contacts.cleanup_import_files',
    domain: 'contacts',
    owner: 'P11',
    description:
      'Retence nahraných souborů importu. Po smazání nastaví imports.storage_key na NULL.',
    cron: '5 3 * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 1 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 2, 4.6 (název odvozen P01)',
  },
  {
    name: 'contact_fields.build_index',
    domain: 'contacts',
    owner: 'P07',
    description:
      'Založí částečný výrazový index pro pole označené indexed přes CREATE INDEX CONCURRENTLY.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 2 * HOUR,
    singletonKeyTemplate: '<field_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'field_id'],
    source: 'část 2, 4.2',
  },
  {
    name: 'segments.recount',
    domain: 'contacts',
    owner: 'P11',
    description: 'Přepočet počtu členů segmentu.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 30 * MINUTE,
    singletonKeyTemplate: '<segment_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'segment_id'],
    source: 'část 2, 5.4',
  },
  {
    name: 'segments.mark_invalid',
    domain: 'contacts',
    owner: 'P11',
    description: 'Označí segmenty odkazující na smazané pole jako neplatné.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 15 * MINUTE,
    deadLetter: true,
    payloadFields: ['workspace_id', 'field_key'],
    source: 'část 2, 4.2',
  },
  {
    name: 'segments.recalc_for_contact',
    domain: 'contacts',
    owner: 'P11',
    description: 'Přepočet příslušnosti jednoho kontaktu k segmentům po události.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 15,
    expireInSeconds: 5 * MINUTE,
    deadLetter: true,
    payloadFields: ['workspace_id', 'contact_id'],
    source: 'část 5, 3.9.2',
  },
  {
    name: 'gdpr.export_subject',
    domain: 'contacts',
    owner: 'P07',
    description: 'Sestaví ZIP s daty subjektu.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 2 * HOUR,
    singletonKeyTemplate: '<request_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'request_id'],
    source: 'část 2, 6.4',
  },
  {
    name: 'gdpr.erase',
    domain: 'contacts',
    owner: 'P07',
    description: 'Anonymizace kontaktu podle článku 17.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 1 * HOUR,
    singletonKeyTemplate: '<request_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'request_id', 'contact_id'],
    source: 'část 2, 6.5',
  },
  {
    name: 'gdpr.sever_links',
    domain: 'contacts',
    owner: 'P07',
    description: 'Odpojí vazby na kontakt v messages, web_events a message_engagement.',
    retryLimit: 5,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 2 * HOUR,
    singletonKeyTemplate: '<contact_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'contact_id'],
    source: 'část 2, 6.5',
  },
  {
    name: 'inbound.process',
    domain: 'contacts',
    owner: 'P07',
    description: 'Zpracuje přijaté tělo příchozího webhooku po ověření podpisu.',
    retryLimit: 5,
    retryBackoff: true,
    retryDelaySeconds: 15,
    expireInSeconds: 15 * MINUTE,
    singletonKeyTemplate: '<dedup_key>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'delivery_id'],
    source: 'část 2, 5.6 (název odvozen P01)',
  },
  // Tři fronty doplněné po nálezu, že je P07 implementuje ve svém registru
  // CONTACTS_QUEUES, ale v tomhle registru chyběly. Parametry jsou opsané z P07,
  // aby se registry nerozešly. Uzávěr S8: frontu zakládá P01, handler P07.
  {
    name: 'contacts.cleanup_pending',
    domain: 'contacts',
    owner: 'P07',
    description:
      'Maže nepotvrzené odběry po vypršení TTL potvrzovacího tokenu a po třiceti dnech retence.',
    cron: '55 2 * * *',
    retryLimit: 2,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 15 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: true,
    payloadFields: [],
    source: 'část 2, 3.4',
  },
  {
    name: 'consents.rebuild_state',
    domain: 'contacts',
    owner: 'P07',
    description:
      'Přepočte contact_consent_state z append only logu consents po obnově ze zálohy nebo po migraci.',
    retryLimit: 2,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 30 * MINUTE,
    singletonKeyTemplate: '<workspace_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'contact_id'],
    source: 'část 2, 3.3',
  },
  // retention.run se spouští pro každý projekt zvlášť s rozprostřením v čase
  // (offset z hashe workspace_id), takže cron plánuje jen dispečera; jednotlivé
  // běhy zakládá handler s singletonKey = workspace_id.
  {
    name: 'retention.run',
    domain: 'contacts',
    owner: 'P07',
    description:
      'Denní retenční běh nad jedním projektem podle registru RETENTION_TARGETS, zapisuje do retention_runs.',
    cron: '20 4 * * *',
    retryLimit: 0,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 40 * MINUTE,
    singletonKeyTemplate: '<workspace_id>',
    deadLetter: false,
    payloadFields: ['workspace_id'],
    source: 'část 2, 6.7',
  },

  // --- Obsah, assety, značka a AI, část 3 -----------------------------------
  {
    name: 'content.brand_extract',
    domain: 'content',
    owner: 'P15',
    description: 'Stažení a analýza značky. Bez opakování, opakovaný SSRF pokus není žádoucí.',
    retryLimit: 0,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 5 * MINUTE,
    singletonKeyTemplate: '<extraction_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'extraction_id'],
    source: 'část 3, 4.8',
  },
  {
    name: 'content.process_asset',
    domain: 'content',
    owner: 'P08',
    description: 'Generování variant obrázku.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 15,
    expireInSeconds: 10 * MINUTE,
    singletonKeyTemplate: '<asset_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'asset_id'],
    source: 'část 3, 4.8',
  },
  {
    name: 'content.revalidate_templates',
    domain: 'content',
    owner: 'P08',
    description: 'Přehodnotí šablony odkazující na smazané pole a označí je jako neplatné.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 30 * MINUTE,
    deadLetter: true,
    payloadFields: ['workspace_id', 'field_key'],
    source: 'část 3, 3.8.4',
  },
  {
    name: 'content.cleanup_versions',
    domain: 'content',
    owner: 'P08',
    description: 'Retence verzí šablon podle TEMPLATE_VERSION_RETENTION_DAYS.',
    cron: '10 3 * * *',
    retryLimit: 1,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 1 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 3, 4.8',
  },
  {
    name: 'content.cleanup_assets',
    domain: 'content',
    owner: 'P08',
    description: 'Fyzické mazání assetů po 30 dnech.',
    cron: '20 3 * * *',
    retryLimit: 1,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 1 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 3, 4.8',
  },
  {
    name: 'content.verify_asset_refcounts',
    domain: 'content',
    owner: 'P08',
    description: 'Kontrola denormalizovaných počtů referencí na assety.',
    cron: '30 3 * * *',
    retryLimit: 1,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 1 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 3, 4.8',
  },
  {
    name: 'ai.cleanup_conversations',
    domain: 'content',
    owner: 'P15',
    description: 'Retence konverzací podle AI_CONVERSATION_RETENTION_DAYS.',
    cron: '40 3 * * *',
    retryLimit: 1,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 1 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 3, 4.8',
  },

  // --- Kampaně, provideři a doručitelnost, část 4a --------------------------
  {
    name: 'campaign.materialize',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Kompilace šablony a materializace publika do outboxu po dávkách.',
    retryLimit: 5,
    retryBackoff: true,
    retryDelaySeconds: 5,
    expireInSeconds: 6 * HOUR,
    singletonKeyTemplate: 'campaign.materialize:<campaign_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'campaign_id', 'revision'],
    source: 'část 4a, 4.5',
  },
  {
    name: 'campaign.scheduler',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Vybírá naplánované kampaně, jejichž čas nastal.',
    cron: '*/30 * * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 5,
    expireInSeconds: 2 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 4a, 4.5',
  },
  {
    name: 'campaign.watchdog',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Rekoncilace stavu běžících kampaní a jejich uzavírání.',
    cron: '*/15 * * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 5,
    expireInSeconds: 1 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 4a, 4.5',
  },
  {
    name: 'campaign.resume_on_quota',
    domain: 'campaigns',
    owner: 'P13',
    description:
      'Obnoví kampaně pozastavené pro vyčerpanou kvótu, rozhoduje podle pause_reason.code.',
    cron: '*/10 * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 5 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 4a, 4.5',
  },
  {
    name: 'outbox.stall_watch',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Hlídá zaseknuté dávky v outboxu.',
    cron: '* * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 10,
    expireInSeconds: 1 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 4a, 4.5',
  },
  {
    name: 'outbox.reconcile',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Srovná počty v outboxu s campaign_stats.',
    cron: '* * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 10,
    expireInSeconds: 5 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 4a, 4.5',
  },
  {
    name: 'provider_event.process',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Zpracuje událost od providera přijatou webhookem.',
    retryLimit: 10,
    retryBackoff: true,
    retryDelaySeconds: 5,
    expireInSeconds: 15 * MINUTE,
    singletonKeyTemplate: 'event:<dedup_key>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'receipt_id', 'dedup_key'],
    source: 'část 4a, 4.5',
  },
  {
    name: 'provider_event.rematch',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Zkusí znovu spárovat události, které při prvním průchodu nenašly zprávu.',
    cron: '*/30 * * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 10,
    expireInSeconds: 5 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 4a, 4.5',
  },
  {
    name: 'provider.refresh_quota',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Načte aktuální kvótu providera.',
    cron: '*/15 * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 5 * MINUTE,
    singletonKeyTemplate: 'provider.quota:<provider_id>',
    deadLetter: false,
    payloadFields: ['workspace_id', 'provider_id'],
    source: 'část 4a, 4.5',
  },
  {
    name: 'domain.recheck',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Kontrola DNS záznamů domén podle next_check_at.',
    cron: '* * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 5 * MINUTE,
    singletonKeyTemplate: 'domain.check:<domain_id>',
    deadLetter: false,
    payloadFields: ['workspace_id', 'domain_id'],
    source: 'část 4a, 4.5',
  },
  {
    name: 'deliverability.rollup',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Agregace ukazatelů doručitelnosti do snapshotů.',
    cron: '*/15 * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 30,
    expireInSeconds: 15 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 4a, 4.5',
  },
  {
    name: 'retention.drop_message_partitions',
    domain: 'campaigns',
    owner: 'P13',
    description: 'Odpojí a zahodí partition messages nad MESSAGE_RETENTION_DAYS.',
    cron: '30 3 * * *',
    retryLimit: 1,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 2 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: true,
    payloadFields: [],
    source: 'část 4a, 4.5',
  },

  // --- Tracking a události, část 5 ------------------------------------------
  {
    name: 'tracking.process_engagement',
    domain: 'tracking',
    owner: 'P10',
    description:
      'Z nových message_events spočítá přírůstky do campaign_stats a message_engagement.',
    retryLimit: 5,
    retryBackoff: true,
    retryDelaySeconds: 5,
    expireInSeconds: 10 * MINUTE,
    concurrency: 4,
    deadLetter: true,
    payloadFields: ['workspace_id', 'event_ids'],
    source: 'část 5, 3.9.2',
  },
  {
    name: 'tracking.process_provider_events',
    domain: 'tracking',
    owner: 'P10',
    description: 'Aktualizuje statistiky z událostí zapsaných providerem.',
    retryLimit: 5,
    retryBackoff: true,
    retryDelaySeconds: 5,
    expireInSeconds: 10 * MINUTE,
    deadLetter: true,
    payloadFields: ['workspace_id', 'event_ids'],
    source: 'část 5, 3.13',
  },
  {
    name: 'event.process',
    domain: 'tracking',
    owner: 'P10',
    description: 'Zpracuje webovou událost, dedup okno 7 dní.',
    retryLimit: 5,
    retryBackoff: true,
    retryDelaySeconds: 5,
    expireInSeconds: 10 * MINUTE,
    deadLetter: true,
    payloadFields: ['workspace_id', 'event_ids'],
    source: 'část 5, 3.9.3',
  },
  {
    name: 'identity.merge',
    domain: 'tracking',
    owner: 'P10',
    description: 'Naváže anonymous_id na kontakt a přepíše historii.',
    retryLimit: 5,
    retryBackoff: true,
    retryDelaySeconds: 10,
    expireInSeconds: 30 * MINUTE,
    singletonKeyTemplate: '<binding_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'anonymous_id', 'contact_id', 'binding_id'],
    source: 'část 5, 3.8.4',
  },
  {
    name: 'tracking.refresh_campaign_progress',
    domain: 'tracking',
    owner: 'P14',
    description: 'Aktualizuje průběh kampaně pro dashboard a SSE.',
    cron: '*/30 * * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 10,
    expireInSeconds: 2 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 5, 3.9',
  },
  {
    name: 'tracking.recompute_engagement_windows',
    domain: 'tracking',
    owner: 'P14',
    description: 'Přepočet klouzavých oken zapojení. Čistá funkce zdrojových dat.',
    cron: '50 3 * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 2 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 5, 3.9.4',
  },
  {
    name: 'tracking.cleanup_token_uses',
    domain: 'tracking',
    owner: 'P10',
    description: 'Maže identity_token_uses s expires_at v minulosti.',
    cron: '0 * * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 15 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 5, 3.10.3',
  },
  {
    name: 'tracking.enforce_retention',
    domain: 'tracking',
    owner: 'P10',
    description: 'Retence web_events a message_events odpojením partition.',
    cron: '45 3 * * *',
    retryLimit: 1,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 2 * HOUR,
    singletonKeyTemplate: 'global',
    deadLetter: true,
    payloadFields: [],
    source: 'část 5, 3.15.2',
  },
  {
    name: 'tracking.refresh_proxy_ranges',
    domain: 'tracking',
    owner: 'P10',
    description: 'Stáhne rozsahy Apple relay, když je TRACKING_APPLE_RELAY_RANGES zapnuté.',
    cron: '0 5 * * *',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 300,
    expireInSeconds: 30 * MINUTE,
    singletonKeyTemplate: 'global',
    deadLetter: false,
    payloadFields: [],
    source: 'část 5, 3.6',
  },
  {
    name: 'tracking.erase_contact',
    domain: 'tracking',
    owner: 'P10',
    description: 'Vymaže stopu kontaktu ve web_events a message_engagement.',
    retryLimit: 5,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 1 * HOUR,
    singletonKeyTemplate: '<contact_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'contact_id'],
    source: 'část 5, 3.15',
  },
  // Doplněno po nálezu: P10 tuhle frontu implementuje a P16 ji volá z CLI
  // (`mlain rebuild-engagement`), ale v registru chyběla. Bez opakování
  // schválně: rekonstrukce od nuly běží nad celým projektem a opakovaný běh
  // po selhání uprostřed by jen zdvojnásobil zátěž. Operátor ji pustí znovu sám.
  {
    name: 'tracking.rebuild_engagement',
    domain: 'tracking',
    owner: 'P10',
    description:
      'Rekonstrukce contact_engagement od nuly ze zdroje pravdy message_engagement po havárii nebo obnově zálohy.',
    retryLimit: 0,
    retryBackoff: false,
    retryDelaySeconds: 0,
    expireInSeconds: 2 * HOUR,
    concurrency: 1,
    singletonKeyTemplate: '<workspace_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'batch_size'],
    source: 'část 5, 3.9.4 a kritérium 77',
  },

  // --- Sender, část 4b ------------------------------------------------------
  // Sender je Go proces s vlastní smyčkou nad outboxem a pg-boss nepoužívá.
  // Jediná fronta, kterou jeho provoz zakládá na straně aplikace, je tahle.
  {
    name: 'sender.credentials_refresh',
    domain: 'sender',
    owner: 'P13',
    description:
      'Přešifruje a znovu publikuje credentials providera po rotaci klíče, aby je sender načetl.',
    retryLimit: 3,
    retryBackoff: true,
    retryDelaySeconds: 60,
    expireInSeconds: 30 * MINUTE,
    singletonKeyTemplate: '<provider_id>',
    deadLetter: true,
    payloadFields: ['workspace_id', 'provider_id'],
    source: 'část 4b, 3.13 a část 1, 3.10 (název odvozen P01)',
  },
];

const BY_NAME = new Map(QUEUE_REGISTRY.map((entry) => [entry.name, entry]));

export function queueNames(): string[] {
  return QUEUE_REGISTRY.map((entry) => entry.name);
}

export function queue(name: string): QueueEntry {
  const entry = BY_NAME.get(name);
  if (!entry) {
    throw new Error(
      `Neregistrovaná fronta "${name}". Fronty se zakládají výhradně v plánu P01, uzávěr S8.`,
    );
  }
  return entry;
}

export function dlqName(name: string): string {
  return `${name}.dlq`;
}

export function cronQueues(): (QueueEntry & { cron: string })[] {
  return QUEUE_REGISTRY.filter(
    (entry): entry is QueueEntry & { cron: string } => typeof entry.cron === 'string',
  );
}

/** Modul s handlerem, který codegen workeru hledá. */
export function handlerModulePath(entry: QueueEntry): string {
  const [domainPart] = entry.name.split('.');
  return `packages/core/src/${domainPart}/jobs/queue-handlers.ts`;
}
