import type { FindingCodeEntry, ProblemCodeEntry } from './types';

/**
 * Katalog kořenových kódů `code` z application/problem+json.
 *
 * Zdroje: část 1, kapitola 4.2 (platformní katalog a katalog části 4a);
 * část 3, kapitoly 3.x a 4.x; část 5, kapitola 4.
 *
 * Pravidla pro `source: 'derived'`, tedy pro kódy, kde specifikace status
 * neuvádí: *_not_found -> 404, *_locked a *_already_* -> 409, *_not_allowed
 * a *_forbidden -> 403, *_rate_limited -> 429, *_timeout -> 504, jinak 422.
 */
export const PROBLEM_CODES: readonly ProblemCodeEntry[] = [
  // --- Platforma, část 1, kapitola 4.2 --------------------------------------
  {
    code: 'unauthenticated',
    status: 401,
    title: 'Unauthenticated',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'invalid_credentials',
    status: 401,
    title: 'Invalid credentials',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'session_expired',
    status: 401,
    title: 'Session expired',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'signature_invalid',
    status: 401,
    title: 'Invalid signature',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'forbidden',
    status: 403,
    title: 'Forbidden',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'insufficient_scope',
    status: 403,
    title: 'Insufficient scope',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'origin_not_allowed',
    status: 403,
    title: 'Origin not allowed',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'csrf_token_invalid',
    status: 403,
    title: 'Invalid CSRF token',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'not_found',
    status: 404,
    title: 'Not found',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'method_not_allowed',
    status: 405,
    title: 'Method not allowed',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'conflict',
    status: 409,
    title: 'Conflict',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'already_exists',
    status: 409,
    title: 'Already exists',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'invalid_state_transition',
    status: 409,
    title: 'Invalid state transition',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'idempotency_key_reuse',
    status: 409,
    title: 'Idempotency key reused',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'idempotency_request_in_progress',
    status: 409,
    title: 'Request in progress',
    retryable: true,
    retryAfterSeconds: 1,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'last_owner_cannot_be_removed',
    status: 409,
    title: 'Last owner cannot be removed',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'setup_already_completed',
    status: 409,
    title: 'Setup already completed',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  // Oba doplněné po nálezu P06: jeho test `mapa kódů na klíče` vyžaduje, aby
  // každý klíč AUTH_ERROR_KEYS a SETTINGS_ERROR_KEYS byl v registru, a tyhle
  // dva v něm chyběly. Zavádí je část 1, kapitoly 3.3 a 3.8.
  {
    code: 'already_member',
    status: 409,
    title: 'User is already a member',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'webhook_endpoint_disabled',
    status: 409,
    title: 'Webhook endpoint is disabled',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'gone',
    status: 410,
    title: 'Gone',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'endpoint_removed',
    status: 410,
    title: 'Endpoint removed',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'precondition_failed',
    status: 412,
    title: 'Precondition failed',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'payload_too_large',
    status: 413,
    title: 'Payload too large',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'unsupported_media_type',
    status: 415,
    title: 'Unsupported media type',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'validation_failed',
    status: 422,
    title: 'Validation failed',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'too_many_items',
    status: 422,
    title: 'Too many items',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'unsupported_api_version',
    status: 422,
    title: 'Unsupported API version',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'account_locked',
    status: 423,
    title: 'Account locked',
    retryable: true,
    retryAfterSeconds: 900,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'resource_locked',
    status: 423,
    title: 'Resource locked',
    retryable: true,
    retryAfterSeconds: 5,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'rate_limited',
    status: 429,
    title: 'Rate limit exceeded',
    retryable: true,
    retryAfterSeconds: 60,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'quota_exceeded',
    status: 429,
    title: 'Quota exceeded',
    retryable: true,
    retryAfterSeconds: 3600,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'internal_error',
    status: 500,
    title: 'Internal server error',
    retryable: true,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'not_implemented',
    status: 501,
    title: 'Not implemented',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'service_unavailable',
    status: 503,
    title: 'Service unavailable',
    retryable: true,
    retryAfterSeconds: 30,
    domain: 'platform',
    source: 'spec',
  },
  {
    code: 'migration_failed',
    status: 503,
    title: 'Migration failed',
    retryable: false,
    domain: 'platform',
    source: 'spec',
  },
  /**
   * Instalace nemá čím odeslat systémový e-mail.
   *
   * Vlastní kód, ne `service_unavailable`, protože příčina není výpadek, ale
   * chybějící nastavení, a odpověď na ni je jiná: přidat účet typu SMTP, ne
   * počkat a zkusit znovu. `retryable` je proto `false`. 503 je záměr: operace
   * neselhala vinou toho, kdo ji vyvolal, a data se nezměnila.
   */
  {
    code: 'system_mail_unavailable',
    status: 503,
    title: 'System mail is not configured',
    retryable: false,
    domain: 'platform',
    source: 'derived',
  },
  {
    code: 'dependency_timeout',
    status: 504,
    title: 'Dependency timeout',
    retryable: true,
    retryAfterSeconds: 5,
    domain: 'platform',
    source: 'spec',
  },

  // --- Kampaně, provideři a doručitelnost, část 4a --------------------------
  {
    code: 'campaign_locked',
    status: 409,
    title: 'Campaign is locked',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_audience_changed',
    status: 409,
    title: 'Campaign audience changed',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_undo_window_expired',
    status: 409,
    title: 'Undo window expired',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_audience_empty',
    status: 422,
    title: 'Campaign audience is empty',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_audience_all_pending',
    status: 422,
    title: 'Campaign audience has only unconfirmed subscribers',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_audience_too_large',
    status: 422,
    title: 'Campaign audience too large',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_not_compiled',
    status: 422,
    title: 'Campaign template not compiled',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_subject_missing',
    status: 422,
    title: 'Campaign subject is missing',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_no_unsubscribe',
    status: 422,
    title: 'Template has no unsubscribe link',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_unknown_merge_field',
    status: 422,
    title: 'Template references unknown field',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_schedule_too_soon',
    status: 422,
    title: 'Scheduled time is too soon',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_schedule_too_far',
    status: 422,
    title: 'Scheduled time is too far ahead',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_not_sendable',
    status: 422,
    title: 'Campaign is not sendable',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'campaign_audience_query_too_slow',
    status: 504,
    title: 'Audience query timed out',
    retryable: true,
    retryAfterSeconds: 30,
    domain: 'campaigns',
    source: 'derived',
  },
  {
    code: 'provider_not_ready',
    status: 422,
    title: 'Sending provider is not ready',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_sending_paused',
    status: 422,
    title: 'Provider sending is paused',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_quota_exceeded',
    status: 422,
    title: 'Provider daily quota exceeded',
    retryable: true,
    retryAfterSeconds: 3600,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_sandbox',
    status: 422,
    title: 'Provider account is in sandbox',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_credentials_invalid',
    status: 422,
    title: 'Provider credentials are invalid',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_smtp_host_unknown',
    status: 422,
    title: 'SMTP host is unknown',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_smtp_connection_refused',
    status: 422,
    title: 'SMTP connection refused',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_smtp_tls_invalid',
    status: 422,
    title: 'SMTP TLS handshake failed',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_smtp_auth_failed',
    status: 422,
    title: 'SMTP authentication failed',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_smtp_timeout',
    status: 422,
    title: 'SMTP connection timed out',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  // Doplněné po nálezu P13: jeho seznam REQUIRED_ERROR_CODES tyhle dva vyžaduje
  // a v registru chyběly, takže jeho test předpokladů padal na startu plánu.
  {
    code: 'provider_smtp_starttls_unsupported',
    status: 422,
    title: 'SMTP server does not support STARTTLS',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'provider_smtp_greeting_invalid',
    status: 422,
    title: 'SMTP greeting is invalid',
    retryable: true,
    domain: 'campaigns',
    source: 'spec',
  },
  // Rozhodnutí R5: contract_mismatch je v MESSAGE_CODES jako stav zprávy, ale
  // P13 ho potřebuje i jako HTTP kód, protože kontrolu z jeho úkolu 47 vrací API.
  // Tentýž kód ve dvou prostorech je povolený, když má v obou význam.
  {
    code: 'contract_mismatch',
    status: 422,
    title: 'Contract mismatch between compiled template and outbox',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'domain_dkim_missing',
    status: 422,
    title: 'Domain DKIM is not verified',
    retryable: true,
    retryAfterSeconds: 300,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'domain_spf_missing',
    status: 422,
    title: 'Domain SPF record is missing',
    retryable: true,
    retryAfterSeconds: 300,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'domain_dmarc_missing',
    status: 422,
    title: 'Domain DMARC record is missing',
    retryable: true,
    retryAfterSeconds: 300,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'domain_check_rate_limited',
    status: 429,
    title: 'Domain check rate limited',
    retryable: true,
    retryAfterSeconds: 60,
    domain: 'campaigns',
    source: 'derived',
  },
  {
    code: 'test_recipient_suppressed',
    status: 422,
    title: 'Test recipient is suppressed',
    retryable: false,
    domain: 'campaigns',
    source: 'spec',
  },
  {
    code: 'test_rate_limited',
    status: 429,
    title: 'Test send rate limited',
    retryable: true,
    retryAfterSeconds: 60,
    domain: 'campaigns',
    source: 'derived',
  },

  // --- Transakční pošta přes API -------------------------------------------
  // Vlastní rodina kódů, protože volajícím je APLIKACE ZÁKAZNÍKA, ne naše UI:
  // musí z odpovědi poznat, co má opravit, bez čtení dokumentace.
  {
    code: 'template_kind_not_transactional',
    status: 422,
    title: 'Template is not transactional',
    retryable: false,
    domain: 'campaigns',
    source: 'derived',
  },
  {
    code: 'template_not_compilable',
    status: 422,
    title: 'Template cannot be compiled',
    retryable: false,
    domain: 'campaigns',
    source: 'derived',
  },
  {
    code: 'recipient_suppressed',
    status: 422,
    title: 'Recipient is suppressed',
    retryable: false,
    domain: 'campaigns',
    source: 'derived',
  },
  {
    code: 'recipient_unknown',
    status: 422,
    title: 'Recipient is not a contact',
    retryable: false,
    domain: 'campaigns',
    source: 'derived',
  },
  {
    code: 'transactional_data_too_large',
    status: 413,
    title: 'Transactional data is too large',
    retryable: false,
    domain: 'campaigns',
    source: 'derived',
  },
  {
    code: 'transactional_variable_unknown',
    status: 422,
    title: 'Transactional variable was not supplied',
    retryable: false,
    domain: 'campaigns',
    source: 'derived',
  },
  {
    code: 'sender_identity_not_found',
    status: 422,
    title: 'Sender identity not found',
    retryable: false,
    domain: 'campaigns',
    source: 'derived',
  },
  {
    code: 'sending_not_configured',
    status: 409,
    title: 'Sending is not configured',
    retryable: false,
    domain: 'campaigns',
    source: 'derived',
  },

  // --- Kontakty, souhlasy, segmenty, část 2 --------------------------------
  // Část 2, kapitola 2.3 mapuje své situace na platformní kódy a doménovou
  // příčinu posílá do errors[].code. Vlastní kořenový kód zavádí jen tenhle:
  {
    code: 'contact_limit_reached',
    status: 429,
    title: 'Contact limit reached',
    retryable: false,
    domain: 'contacts',
    source: 'spec',
  },

  // --- Obsah, assety, značka a AI, část 3 ----------------------------------
  {
    code: 'template_document_invalid',
    status: 422,
    title: 'Template document is invalid',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'template_schema_too_new',
    status: 422,
    title: 'Template schema version is too new',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'template_starter_immutable',
    status: 409,
    title: 'Starter template is immutable',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    // Doplněno k filtru knihovny šablon. Formulář a seznam si svůj e-mail berou
    // ze ŽIVÉ šablony při každém odeslání, takže měkké smazání by je umlčelo,
    // aniž by cokoli spadlo. 409, ne 422: požadavek je v pořádku, jen stav
    // projektu ho nedovoluje, a uživatel to napraví odpojením, ne opravou těla.
    code: 'template_in_use',
    status: 409,
    title: 'Template is wired to a form or a list',
    retryable: false,
    domain: 'content',
    source: 'derived',
  },
  {
    // Doplněno pro trasy šablon. Plán P08 (Task 42) ho vyžaduje doslova, jak
    // v mapování chyb, tak ve svém testu („returns 409, not 500, when a name
    // collides"), a `duplicateTemplate` v `templates/service.ts` ho hází jako
    // doménovou chybu. V registru přesto nebyl, takže by kolize jména skončila
    // pětistovkou: `ApiError` neregistrovaný kód odmítne vyrobit.
    //
    // Jde vědomě o `template_name_conflict`, ne o obecný `already_exists`.
    // Uživatel musí poznat, že si má jméno změnit, ne že šablona existuje.
    code: 'template_name_conflict',
    status: 409,
    title: 'Template name already exists',
    retryable: false,
    domain: 'content',
    source: 'derived',
  },
  {
    code: 'content_too_many_blocks',
    status: 413,
    title: 'Too many blocks in document',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'asset_quota_exceeded',
    status: 413,
    title: 'Asset storage quota exceeded',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'asset_too_many_pixels',
    status: 413,
    title: 'Image has too many pixels',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'asset_unsupported_format',
    status: 415,
    title: 'Unsupported asset format',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'asset_corrupt',
    status: 422,
    title: 'Asset file is corrupt',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'asset_referenced_by_sent_campaign',
    status: 409,
    title: 'Asset is referenced by a sent campaign',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_invalid_url',
    status: 400,
    title: 'Brand URL is invalid',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_scheme_not_allowed',
    status: 400,
    title: 'Brand URL scheme is not allowed',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_port_not_allowed',
    status: 400,
    title: 'Brand URL port is not allowed',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_host_not_allowed',
    status: 400,
    title: 'Brand host is not allowed',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_blocked_address',
    status: 400,
    title: 'Brand host resolves to a blocked address',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_credentials_in_url',
    status: 400,
    title: 'Brand URL contains credentials',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_robots_disallowed',
    status: 403,
    title: 'Brand fetch disallowed by robots.txt',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_robots_unavailable',
    status: 422,
    title: 'robots.txt could not be fetched',
    retryable: true,
    retryAfterSeconds: 300,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_dns_failed',
    status: 422,
    title: 'Brand host DNS lookup failed',
    retryable: true,
    retryAfterSeconds: 300,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_fetch_failed',
    status: 422,
    title: 'Brand page could not be fetched',
    retryable: true,
    retryAfterSeconds: 300,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_insecure_redirect',
    status: 422,
    title: 'Brand fetch hit an insecure redirect',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_redirect_loop',
    status: 422,
    title: 'Brand fetch hit a redirect loop',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_too_many_redirects',
    status: 422,
    title: 'Brand fetch exceeded redirect limit',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_response_too_large',
    status: 422,
    title: 'Brand response is too large',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_unexpected_content_type',
    status: 422,
    title: 'Unexpected content type from brand host',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_timeout',
    status: 504,
    title: 'Brand fetch timed out',
    retryable: true,
    retryAfterSeconds: 300,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'brand_extract_running',
    status: 409,
    title: 'Brand extraction already running',
    retryable: true,
    retryAfterSeconds: 30,
    domain: 'content',
    source: 'derived',
  },
  {
    code: 'ai_credential_missing',
    status: 422,
    title: 'AI provider key is not configured',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'ai_invalid_credentials',
    status: 422,
    title: 'AI provider credentials are invalid',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'ai_insufficient_credit',
    status: 422,
    title: 'AI provider reports insufficient credit',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'ai_context_too_long',
    status: 422,
    title: 'AI request context is too long',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'ai_invalid_output',
    status: 422,
    title: 'AI returned output that failed schema validation',
    retryable: true,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'ai_content_filtered',
    status: 422,
    title: 'AI provider filtered the content',
    retryable: false,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'ai_rate_limited',
    status: 429,
    title: 'AI provider rate limited the request',
    retryable: true,
    retryAfterSeconds: 60,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'ai_provider_unavailable',
    status: 503,
    title: 'AI provider is unavailable',
    retryable: true,
    retryAfterSeconds: 60,
    domain: 'content',
    source: 'spec',
  },
  {
    code: 'ai_timeout',
    status: 504,
    title: 'AI request timed out',
    retryable: true,
    retryAfterSeconds: 30,
    domain: 'content',
    source: 'spec',
  },

  // --- Tracking a události, část 5 ------------------------------------------
  {
    code: 'token_malformed',
    status: 400,
    title: 'Tracking token is malformed',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'token_signature_invalid',
    status: 400,
    title: 'Tracking token signature is invalid',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'token_unknown_key',
    status: 400,
    title: 'Tracking token uses an unknown key generation',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'token_type_mismatch',
    status: 400,
    title: 'Tracking token type does not match the endpoint',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_payload_version_unsupported',
    status: 400,
    title: 'Unsupported tracking payload version',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'token_already_used',
    status: 409,
    title: 'One time token has already been used',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_disabled',
    status: 409,
    title: 'Tracking is disabled for this workspace',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_merge_not_revertible',
    status: 409,
    title: 'Identity merge cannot be reverted',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'token_expired',
    status: 410,
    title: 'Tracking token has expired',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_domain_invalid',
    status: 422,
    title: 'Tracking domain is invalid',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_domain_limit_reached',
    status: 422,
    title: 'Tracking domain limit reached',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_event_too_large',
    status: 422,
    title: 'Event payload is too large',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_invalid_event_name',
    status: 422,
    title: 'Event name is invalid',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_invalid_anonymous_id',
    status: 422,
    title: 'Anonymous id is invalid',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_identify_unsigned_pii',
    status: 422,
    title: 'Identify call carries unsigned personal data',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_import_beyond_retention',
    status: 422,
    title: 'Imported events fall outside the retention window',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_import_partition_missing',
    status: 422,
    title: 'Target partition for imported events does not exist',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },
  {
    code: 'tracking_timeline_window_too_large',
    status: 422,
    title: 'Timeline window is too large',
    retryable: false,
    domain: 'tracking',
    source: 'spec',
  },

  // --- Sender jako HTTP aktér, část 4b --------------------------------------
  // Sender vlastní HTTP endpoint jen pro health; jediný kód, který vrací API
  // aplikace kvůli senderu, je tenhle. Ostatní kódy senderu jsou v MESSAGE_CODES.
  {
    code: 'sender_not_running',
    status: 503,
    title: 'Sending service is not running',
    retryable: true,
    retryAfterSeconds: 30,
    domain: 'sender',
    source: 'derived',
  },
];

/**
 * `findings[].code`. Preflight kampaně vrací víc nálezů naráz s vlastní
 * závažností; operace smí vrátit 4xx jen tehdy, když je mezi nálezy aspoň
 * jeden se severity 'error' (část 1, 4.2).
 */
export const FINDING_CODES: readonly FindingCodeEntry[] = [
  { code: 'campaign_no_unsubscribe', severity: 'error', domain: 'campaigns', source: 'spec' },
  { code: 'campaign_subject_missing', severity: 'error', domain: 'campaigns', source: 'spec' },
  { code: 'campaign_unknown_merge_field', severity: 'error', domain: 'campaigns', source: 'spec' },
  { code: 'campaign_audience_empty', severity: 'error', domain: 'campaigns', source: 'spec' },
  // Zvláštní případ prázdného publika: seznam vybraný je a lidé v něm jsou, jenže
  // všichni čekají na potvrzení. Vlastní kód proto, že rada „vyberte seznam" je tady
  // nepoužitelná a uživatel potřebuje slyšet něco jiného.
  { code: 'campaign_audience_all_pending', severity: 'error', domain: 'campaigns', source: 'spec' },
  { code: 'campaign_not_compiled', severity: 'error', domain: 'campaigns', source: 'spec' },
  /*
   * Obsah kampaně ve dvou stavech, ne v jednom. Vzniklo z vady z instalace:
   * kampaň, jejíž dokument neobsahoval nic než patičku, prošla kontrolou před
   * odesláním a na tři adresy dorazil e-mail s pouhými odkazy na odhlášení.
   *
   * `campaign_content_missing` znamená, že dokument vůbec není, tedy že si
   * uživatel obsah ještě nezaložil. `campaign_content_empty` znamená, že dokument
   * je, ale není v něm jediný obsahový blok. Rada je u každého jiná („založte
   * obsah" proti „napište do e-mailu něco"), proto dva kódy a ne jeden.
   */
  { code: 'campaign_content_missing', severity: 'error', domain: 'campaigns', source: 'spec' },
  { code: 'campaign_content_empty', severity: 'error', domain: 'campaigns', source: 'spec' },
  { code: 'provider_not_ready', severity: 'error', domain: 'campaigns', source: 'spec' },
  { code: 'provider_sandbox', severity: 'error', domain: 'campaigns', source: 'spec' },
  { code: 'domain_dkim_missing', severity: 'error', domain: 'campaigns', source: 'spec' },
  { code: 'domain_spf_missing', severity: 'warning', domain: 'campaigns', source: 'spec' },
  { code: 'domain_dmarc_missing', severity: 'warning', domain: 'campaigns', source: 'spec' },
  { code: 'content_missing_unsubscribe', severity: 'error', domain: 'content', source: 'spec' },
  { code: 'content_image_missing_alt', severity: 'warning', domain: 'content', source: 'spec' },
  { code: 'content_low_contrast', severity: 'warning', domain: 'content', source: 'spec' },
  { code: 'content_link_anchor_only', severity: 'warning', domain: 'content', source: 'spec' },
  { code: 'content_too_many_links', severity: 'warning', domain: 'content', source: 'spec' },
  { code: 'content_html_too_large', severity: 'warning', domain: 'content', source: 'spec' },
  { code: 'content_padding_overflow', severity: 'warning', domain: 'content', source: 'spec' },
  { code: 'deliverability_degraded', severity: 'warning', domain: 'campaigns', source: 'derived' },
];
